#!/usr/bin/env bash
set -euo pipefail

# Verify that the harness-side RTL filelist matches the canonical chip-inventory list.
#
# Intended usage (run from harness repo root):
#   ip/home-inventory-chip/tools/harness/check_harness_filelist.sh
#
# You can also pass --harness-root <path>.

usage() {
  cat <<'EOF'
Usage:
  check_harness_filelist.sh [--harness-root <path>] [--diff]

Run from the OpenMPW harness repo root, OR pass --harness-root.

Checks that:
  <harness-root>/verilog/rtl/ip_home_inventory.f
matches the expected content derived from:
  <harness-root>/ip/home-inventory-chip/rtl/ip_home_inventory.f

Options:
  --diff   Show a unified diff on mismatch.
EOF
}

HARNESS_ROOT=""
SHOW_DIFF=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --harness-root)
      HARNESS_ROOT="$2"
      shift 2
      ;;
    --diff)
      SHOW_DIFF=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "${HARNESS_ROOT}" ]]; then
  HARNESS_ROOT="$(pwd)"
fi

CANON_FILELIST="${HARNESS_ROOT}/ip/home-inventory-chip/rtl/ip_home_inventory.f"
HARNESS_FILELIST="${HARNESS_ROOT}/verilog/rtl/ip_home_inventory.f"

if [[ ! -f "${CANON_FILELIST}" ]]; then
  echo "ERROR: canonical filelist not found: ${CANON_FILELIST}" >&2
  echo "Hint: run from harness repo root, or pass --harness-root." >&2
  exit 1
fi

if [[ ! -f "${HARNESS_FILELIST}" ]]; then
  echo "ERROR: harness filelist not found: ${HARNESS_FILELIST}" >&2
  echo "Hint: run gen_harness_filelist.sh first." >&2
  exit 1
fi

EXPECTED="$(mktemp)"
trap 'rm -f "${EXPECTED}"' EXIT

{
  echo "# AUTOGENERATED: do not hand-edit"
  echo "# Source: ip/home-inventory-chip/rtl/ip_home_inventory.f"
  echo "# Generated: <timestamp elided>"
  echo
  while IFS='' read -r line; do
    if [[ -z "${line}" ]] || [[ "${line}" =~ ^[[:space:]]*# ]]; then
      echo "${line}"
    else
      echo "ip/home-inventory-chip/${line}"
    fi
  done < "${CANON_FILELIST}"
} > "${EXPECTED}"

# Normalize the real harness filelist by deleting the volatile Generated timestamp line.
# (We treat timestamps as non-semantic.)
NORMALIZED_REAL="$(mktemp)"
trap 'rm -f "${EXPECTED}" "${NORMALIZED_REAL}"' EXIT

sed -E 's/^# Generated: .*/# Generated: <timestamp elided>/' "${HARNESS_FILELIST}" > "${NORMALIZED_REAL}"

if cmp -s "${EXPECTED}" "${NORMALIZED_REAL}"; then
  echo "OK: harness filelist matches canonical source-of-truth"
  exit 0
fi

echo "ERROR: harness filelist is out of sync with canonical list" >&2
echo "Expected (derived from): ${CANON_FILELIST}" >&2
echo "Actual:   ${HARNESS_FILELIST}" >&2
echo "Fix: run ip/home-inventory-chip/tools/harness/gen_harness_filelist.sh" >&2

if [[ ${SHOW_DIFF} -eq 1 ]]; then
  echo >&2
  diff -u "${EXPECTED}" "${NORMALIZED_REAL}" || true
fi

exit 1
