#!/usr/bin/env bash
set -euo pipefail

# Generate the harness-side RTL filelist from the canonical chip-inventory list.
#
# Intended usage (run from harness repo root):
#   ip/home-inventory-chip/tools/harness/gen_harness_filelist.sh
#
# Output:
#   verilog/rtl/ip_home_inventory.f
#
# Why:
#   Avoid drift between chip-inventory/rtl/ip_home_inventory.f and the harness.

usage() {
  cat <<'EOF'
Usage:
  gen_harness_filelist.sh [--harness-root <path>]

Run from the OpenMPW harness repo root, OR pass --harness-root.

Generates:
  <harness-root>/verilog/rtl/ip_home_inventory.f
from:
  <harness-root>/ip/home-inventory-chip/rtl/ip_home_inventory.f
EOF
}

HARNESS_ROOT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --harness-root)
      HARNESS_ROOT="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "${HARNESS_ROOT}" ]]; then
  HARNESS_ROOT="$(pwd)"
fi

CANON_FILELIST="${HARNESS_ROOT}/ip/home-inventory-chip/rtl/ip_home_inventory.f"
OUT_FILELIST="${HARNESS_ROOT}/verilog/rtl/ip_home_inventory.f"

if [[ ! -f "${CANON_FILELIST}" ]]; then
  echo "ERROR: canonical filelist not found: ${CANON_FILELIST}" >&2
  echo "Hint: run from harness repo root, or pass --harness-root." >&2
  exit 1
fi

if [[ ! -d "${HARNESS_ROOT}/verilog/rtl" ]]; then
  echo "ERROR: expected harness directory missing: ${HARNESS_ROOT}/verilog/rtl" >&2
  echo "Hint: pass --harness-root to the harness repo root." >&2
  exit 1
fi

TMP_OUT="$(mktemp)"
trap 'rm -f "${TMP_OUT}"' EXIT

{
  echo "# AUTOGENERATED: do not hand-edit"
  echo "# Source: ip/home-inventory-chip/rtl/ip_home_inventory.f"
  echo "# Generated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  echo
  # Prefix each path with the submodule location.
  # Keep blank lines and comments as-is.
  while IFS='' read -r line; do
    if [[ -z "${line}" ]] || [[ "${line}" =~ ^[[:space:]]*# ]]; then
      echo "${line}"
    else
      echo "ip/home-inventory-chip/${line}"
    fi
  done < "${CANON_FILELIST}"
} > "${TMP_OUT}"

# Only update the destination if it changed (keeps git diffs clean).
if [[ -f "${OUT_FILELIST}" ]] && cmp -s "${TMP_OUT}" "${OUT_FILELIST}"; then
  echo "OK: harness filelist already up-to-date: ${OUT_FILELIST}"
  exit 0
fi

mv "${TMP_OUT}" "${OUT_FILELIST}"
chmod 0644 "${OUT_FILELIST}"

echo "OK: wrote ${OUT_FILELIST}"
