#!/usr/bin/env python3
"""gen_verilog_params.py

Generate a Verilog include file containing ADR_* localparams from the
single source-of-truth YAML register map.

This reduces manual drift between RTL decode constants and the spec.

Usage:
  python3 tools/regmap/gen_verilog_params.py \
    --yaml spec/regmap_v1.yaml \
    --out  rtl/include/regmap_params.vh

Notes:
  - Output uses byte addresses (Wishbone wbs_adr_i).
  - All addresses are 32-bit word-aligned.
  - The include is intended to be consumed by rtl/home_inventory_wb.v.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml


def load_regs(yaml_path: Path) -> list[tuple[str, int]]:
    data = yaml.safe_load(yaml_path.read_text())
    if not isinstance(data, dict) or "blocks" not in data:
        raise ValueError(f"Unexpected YAML shape in {yaml_path}")

    regs: list[tuple[str, int]] = []

    for blk in data.get("blocks", []):
        base = int(str(blk.get("base", "0")), 0)
        for r in blk.get("registers", []):
            name = r.get("name")
            if not name:
                raise ValueError(f"register missing name in block {blk.get('name')!r}")
            offset = int(str(r.get("offset", "0")), 0)
            addr = base + offset
            if addr % 4 != 0:
                raise ValueError(f"{name} address 0x{addr:08X} not word-aligned")
            regs.append((f"ADR_{name}", addr))

    # stable ordering: by address, then name
    regs.sort(key=lambda kv: (kv[1], kv[0]))

    # uniqueness
    names = [n for n, _ in regs]
    if len(set(names)) != len(names):
        raise ValueError("duplicate register names found")
    addrs = [a for _, a in regs]
    if len(set(addrs)) != len(addrs):
        raise ValueError("duplicate register addresses found")

    return regs


def emit(out_path: Path, yaml_path: Path, regs: list[tuple[str, int]]) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Keep a stable, repo-root relative source path when generating from the
    # canonical spec file, even if invoked from subdirectories.
    gen_from = "spec/regmap_v1.yaml" if yaml_path.name == "regmap_v1.yaml" else yaml_path.as_posix()

    lines: list[str] = []
    lines.append("// AUTOGENERATED FILE -- DO NOT EDIT")
    lines.append(f"// Source: {gen_from}")
    lines.append("// Generated by: tools/regmap/gen_verilog_params.py")
    lines.append("")
    lines.append("// Address map (byte addresses)")

    for name, addr in regs:
        lines.append(f"localparam [31:0] {name:<22} = 32'h{addr:08X};")

    lines.append("")

    out_path.write_text("\n".join(lines))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--yaml", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    regs = load_regs(args.yaml)
    emit(args.out, args.yaml, regs)
    print(f"Wrote {len(regs)} localparams to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
